# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HHR' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HHR

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'FBSDKLoginKit'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'GeoFire'
pod 'Cosmos', '~> 16.0'

	target 'HHRTests' do
        	inherit! :search_paths
        	pod 'Firebase/Core'
		pod 'Firebase/Auth'
		pod 'Firebase/Database'
		pod 'Firebase/Storage'
		pod 'FBSDKLoginKit'
		pod 'FBSDKCoreKit'
		pod 'FBSDKShareKit'
		pod 'GeoFire'
		pod 'Cosmos', '~> 16.0'
    end

end
